package: mailer_profile
version: '0.1-dev' 
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/mailer_profile

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        mailer: ^2.11
        yform: "^4"


page:
    title: translate:mailer_profile_title
    icon: rex-icon fa-gear

pages:
    phpmailer/profile:
        title: translate:mailer_profile_title
        perm: mailer_profile[]
    docs:
        title: translate:mailer_profile_docs
        subPath: README.md 
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: mailer_profile[docs]
