package: mailer_profile
version: '1.3.0'
author: 'Alexander Walther, Stefan Dannfald' 
supportpage: https://github.com/alexplusde/mailer_profile

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        phpmailer: ^2.11
        yform: "^4"


page:
    hidden: true
    title: translate:mailer_profile_title


pages:
    phpmailer/profile:
        title: translate:mailer_profile_title
        perm: mailer_profile[]
    docs:
        title: translate:mailer_profile_docs
        subPath: README.md 
        icon: rex-icon fa-info-circle
        itemClass: pull-right
        perm: mailer_profile[docs]
